const TOGGLE_APP_LOADING = 'TOGGLE_APP_LOADING';
const RESET_APP_LOADING = 'RESET_APP_LOADING';

const HOME_ACTIONS = {
  SET_PRACTICES: 'SET_PRACTICES',
  SET_MAP_COORDINATES: "SET_MAP_COORDINATES"
};

export default {
  TOGGLE_APP_LOADING,
  RESET_APP_LOADING,
  HOME_ACTIONS
};
